"""new rename: including_vacant_units

Revision ID: 0d4902a47e00
Revises: 32d3d8951815
Create Date: 2025-03-29 00:38:13.342980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4902a47e00'
down_revision = '32d3d8951815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None, recreate='always') as batch_op:
        batch_op.drop_index('ix_groups_occupied_only')
        batch_op.alter_column(column_name='occupied_only', new_column_name='including_vacant_units')
        # batch_op.create_index(batch_op.f('ix_groups_including_vacant_units'), ['including_vacant_units'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None, recreate='always') as batch_op:
        # batch_op.drop_index(batch_op.f('ix_groups_including_vacant_units'))
        batch_op.alter_column(column_name='including_vacant_units', new_column_name='occupied_only')
        batch_op.create_index('ix_groups_occupied_only', ['occupied_only'], unique=False)

    # ### end Alembic commands ###
