"""added: cash_reserves table under building

Revision ID: 10d0b367eae5
Revises: 7bdcab2edd70
Create Date: 2025-03-26 14:24:56.075331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d0b367eae5'
down_revision = '7bdcab2edd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_reserves',
    sa.Column('cash_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], name=op.f('fk_cash_reserves_building_id_buildings'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('cash_id', name=op.f('pk_cash_reserves'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash_reserves')
    # ### end Alembic commands ###
