"""column rename: cashreserve primary key

Revision ID: 1116f0f4b2bf
Revises: 81c3016a652c
Create Date: 2025-03-27 09:58:29.174311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1116f0f4b2bf'
down_revision = '81c3016a652c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_reserves', schema=None) as batch_op:
        batch_op.alter_column(column_name='cash_id', new_column_name='reserve_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_reserves', schema=None) as batch_op:
        batch_op.alter_column(new_column_name='cash_id', column_name='reserve_id')

    # ### end Alembic commands ###
