"""rename column: allotting spelling! alloting_to_people

Revision ID: 32d3d8951815
Revises: b490a732c104
Create Date: 2025-03-28 17:44:25.638000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d3d8951815'
down_revision = 'b490a732c104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index('ix_groups_alloting_by')
        batch_op.alter_column(column_name='alloting_by', new_column_name='allotting_to_people')

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_column('last_settled_period')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_settled_period', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column(column_name='allotting_to_people', new_column_name='alloting_by')
        batch_op.create_index('ix_groups_alloting_by', ['alloting_by'], unique=False)

    # ### end Alembic commands ###
