"""set members_shares back to dict-json

Revision ID: 566652f978b6
Revises: 748d1e425441
Create Date: 2025-03-19 13:47:21.476794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566652f978b6'
down_revision = '748d1e425441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer()))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('members_shares',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('members_shares',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
