"""forgot 1 NULL constraint!

Revision ID: 5ded6ff114c7
Revises: 44500fdda18a
Create Date: 2025-03-30 17:22:44.418318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ded6ff114c7'
down_revision = '44500fdda18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_group_id_groups', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_expenses_group_id_groups'), 'groups', ['group_id'], ['group_id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_expenses_group_id_groups'), type_='foreignkey')
        batch_op.create_foreign_key('fk_expenses_group_id_groups', 'groups', ['group_id'], ['group_id'], onupdate='CASCADE', ondelete='SET NULL')

    # ### end Alembic commands ###
