"""relationship unit->shares

Revision ID: 7bdcab2edd70
Revises: 8adcc86be407
Create Date: 2025-03-25 14:10:12.003699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdcab2edd70'
down_revision = '8adcc86be407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_shares')
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_shares_unit_number')
        batch_op.create_foreign_key(batch_op.f('fk_shares_unit_id_units'), 'units', ['unit_id'], ['unit_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('unit_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_number', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_shares_unit_id_units'), type_='foreignkey')
        batch_op.create_index('ix_shares_unit_number', ['unit_number'], unique=False)
        batch_op.drop_column('unit_id')

    op.create_table('_alembic_tmp_shares',
    sa.Column('share_id', sa.INTEGER(), nullable=False),
    sa.Column('period', sa.INTEGER(), nullable=False),
    sa.Column('unit_number', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('expense_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('unit_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.expense_id'], name='fk_shares_expense_id_expenses', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], name='fk_shares_unit_id_units', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('share_id', name='pk_shares')
    )
    # ### end Alembic commands ###
