"""shares.period changed to shares.paid(bool)

Revision ID: 81c3016a652c
Revises: 10d0b367eae5
Create Date: 2025-03-26 19:09:08.775791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c3016a652c'
down_revision = '10d0b367eae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_shares')
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=False, default=False))
        batch_op.drop_index('ix_shares_period')
        batch_op.create_index(batch_op.f('ix_shares_paid'), ['paid'], unique=False)
        batch_op.drop_column('period')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_shares_paid'))
        batch_op.create_index('ix_shares_period', ['period'], unique=False)
        batch_op.drop_column('paid')

    op.create_table('_alembic_tmp_shares',
    sa.Column('share_id', sa.INTEGER(), nullable=False),
    sa.Column('paid', sa.BOOLEAN(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('expense_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('unit_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.expense_id'], name='fk_shares_expense_id_expenses', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], name='fk_shares_unit_id_units', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('share_id', name='pk_shares')
    )
    # ### end Alembic commands ###
