"""group table updated

Revision ID: 864655696bbc
Revises: b9be230562ec
Create Date: 2025-03-27 21:36:32.386734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864655696bbc'
down_revision = 'b9be230562ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('alloting_by',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('occupied_only',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('occupied_only',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('alloting_by',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
