"""expense fk cascade and repr for all

Revision ID: 8adcc86be407
Revises: e3ac92d236d1
Create Date: 2025-03-25 13:20:07.960579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8adcc86be407'
down_revision = 'e3ac92d236d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('last_settled_period',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('last_settled_period',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
