"""new relationship: group->expense

Revision ID: b490a732c104
Revises: 864655696bbc
Create Date: 2025-03-27 22:33:17.286338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b490a732c104'
down_revision = '864655696bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_expenses_group_id_groups'), 'groups', ['group_id'], ['group_id'], onupdate='CASCADE', ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_expenses_group_id_groups'), type_='foreignkey')

    # ### end Alembic commands ###
