"""cleaned

Revision ID: c410dc9b9e1b
Revises: f9bb872dc124
Create Date: 2025-03-22 12:41:11.562455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c410dc9b9e1b'
down_revision = 'f9bb872dc124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payer', sa.String(), nullable=False))
        batch_op.drop_index('ix_transaction_sender')
        batch_op.create_index(batch_op.f('ix_transaction_payer'), ['payer'], unique=False)
        batch_op.drop_column('sender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_transaction_payer'))
        batch_op.create_index('ix_transaction_sender', ['sender'], unique=False)
        batch_op.drop_column('payer')

    # ### end Alembic commands ###
